{
  id: 'false_6281214000838@c.us_4AE26921999A6FDBB0DF192953329705',
  rowId: 999999487,
  body: 'Nanti kalau sudah oke akan saya infokan ya kak',
  type: 'chat',
  t: 1689079491,
  from: '6281214000838@c.us',
  to: '6289696664088@c.us',
  self: 'in',
  ack: 0,
  invis: true,
  star: false,
  kicNotified: false,
  streamingSidecar: null,
  waveform: null,
  scanLengths: null,
  scansSidecar: null,
  isFromTemplate: false,
  pollOptions: [],
  pollInvalidated: false,
  latestEditMsgKey: null,
  latestEditSenderTimestampMs: null,
  broadcast: false,
  mentionedJidList: [],
  groupMentions: [],
  hydratedButtons: null,
  isVcardOverMmsDocument: false,
  isForwarded: false,
  hasReaction: false,
  ephemeralOutOfSync: false,
  productHeaderImageRejected: false,
  lastPlaybackProgress: 0,
  isDynamicReplyButtonsMsg: false,
  dynamicReplyButtons: null,
  isMdHistoryMsg: true,
  stickerSentTs: 0,
  isAvatar: false,
  lastUpdateFromServerTs: 0,
  requiresDirectConnection: false,
  invokedBotWid: null,
  chatId: {
    server: 'c.us',
    user: '6281214000838',
    _serialized: '6281214000838@c.us'
  },
  fromMe: false,
  sender: {
    id: [Object],
    type: 'in',
    verifiedName: 'PS Enterprise Service',
    isBusiness: true,
    isEnterprise: false,
    isSmb: true,
    verifiedLevel: 0,
    privacyMode: null,
    isContactSyncCompleted: 1,
    isUser: true,
    profilePicThumbObj: [Object],
    msgs: null
  },
  timestamp: 1689079491,
  content: 'Nanti kalau sudah oke akan saya infokan ya kak',
  chat: {},
  mediaData: {},
  replyButtons: null,
  buttons: null,
  isGroupMsg: false,
  groupInfo: null,
  reply: {}
}
