name: build
on:
  workflow_dispatch:
  pull_request:
    branches: ["*", "!latest"]
  push:
    branches: [latest, main]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Setup Yarn
        run: |
          corepack enable
          corepack prepare yarn@stable --activate

      - name: Cache deps
        uses: actions/cache@v3.3.1
        with:
          path: .yarn
          key: yarn-${{ runner.os }}-${{ hashFiles('yarn.lock') }}

      - name: Install deps
        run: yarn install

      - name: Check format
        run: yarn format

      - name: Check lint
        run: yarn lint

      - name: Clean Project
        run: yarn clean

      - name: Build project
        run: yarn build

      - name: Test project
        run: yarn test

      - name: Check diff
        run: git diff --exit-code HEAD
