name: build
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  build:
    runs-on: macos-14
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2

      - name: Install Setuptools
        run: brew install python-setuptools

      - name: Setup pnpm
        uses: threeal/setup-pnpm-action@v1.0.0

      - name: Install Dependencies
        run: pnpm install

      - name: Check formatting
        run: pnpm prettier --check .

      - name: Check lint
        run: pnpm eslint

      - name: Build project
        run: pnpm tsc
