name: build
on:
  workflow_dispatch:
  pull_request:
    branches: ['*', '!latest']
  push:
    branches: [latest, main]
jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3

      - name: Cache deps
        uses: actions/cache@v3.3.1
        with:
          path: node_modules
          key: node-${{ runner.os }}-${{ hashFiles('package-lock.json') }}

      - name: Install deps
        run: npm install

      - name: Check format
        run: npm run format

      - name: Check lint
        run: npm run lint

      - name: Clean Project
        run: npm run clean

      - name: Build project
        run: npm run build

      - name: Test project
        run: npm test

      - name: Check diff
        run: git diff --exit-code HEAD
